### ISSUE TITLE
Maintain api.sap.com

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-identity-services#22]
### Issue description

Please make sure all configuration authentication methods are up to date (Basic Auth or OAuth Client Credentials? + missing mTLS).

https://api.sap.com/package/SCPIdentityServices/rest

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

API Authentication

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/identity-authentication/identity-authentication/dev-api-authentication?locale=en-US

**Comment by piejanssens** [comment]
In addition, on SAP Help I'm not able to find documentation on how mTLS can be used to access IAS and IPS REST API's.
https://help.sap.com/docs/identity-authentication/identity-authentication/add-administrators?locale=en-US

**Comment by ValAta** [comment]
Hi @piejanssens , is this comment related to https://api.sap.com/package/SCPIdentityServices/rest? 
BR
