### ISSUE TITLE
Link to 'SAP Analytics Cloud: User and Team Provisioning API' not found

### ISSUE THREAD

**Issue by KaloyanVeleshki** [SAP-docs/btp-cloud-identity-services#28]
### Issue description

Section Procedure [SAP Analytics Cloud: User and Team Provisioning API](https://help.sap.com/viewer/298f82da4b184d1fb825b7ffe365e94a/release/en-US/36c9929c050e428ba6b391bf16b018fc.html) which is not working.

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

SAP Analytics Cloud

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/identity-authentication/identity-authentication/sap-analytics-cloud-2220f847ef8642d18f4ecc59a943ff4d?locale=en-US

**Comment by IvelinaKiryakova** [comment]
Thank you @KaloyanVeleshki for noticing the broken link. This has been fixed and released productively at: https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/proxy-sap-analytics-cloud.

Best regards,
Ivelina
