### ISSUE TITLE
Link not available

### ISSUE THREAD

**Issue by stecherb** [SAP-docs/btp-cloud-identity-services#33]
### Issue description

Chapter "Prerequisites": link not available.
--> [Permissions](https://help.sap.com/viewer/28bc3c8e3f214ab487ec51b1b8709adc/latest/en-US/3d71f690709243db99102127557a3d73.html)

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

SAP SuccessFactors

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/proxy-sap-successfactors?locale=en-US

**Comment by stecherb** [comment]
1425074

**Comment by IvelinaKiryakova** [comment]
Thank you for noticing the broken link. It has been fixed now. The documentation will be released next week. 

Best regards,
Ivelina
