### ISSUE TITLE
Missing "possible values" and sf.user.attributes for SCIM API

### ISSUE THREAD

**Issue by stecherb** [SAP-docs/btp-cloud-identity-services#34]
### Issue description

Hi,

On the page: https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/list-of-properties?locale=en-US filter = sf.user.attributes

are no "possible values" listed.

Also the entry references to OData API, what about the SCIM API?

Best regards

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

List of Properties

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/list-of-properties?locale=en-US

**Comment by IvelinaKiryakova** [comment]
Thank you for your feedback. The documentation for sf.user.filter property has been adjusted.
Note that when listing possible values, the Identity Provisioning documentation refers to the SAP SuccessFactors APIs documentation where all supported filtering attributes are described. In most cases we provide only examples. The full list is maintained by the corresponding SAP solution.

Best regards,
Ivelina
