### ISSUE TITLE
oauth2-configuration parameter grant-types not documented

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/btp-cloud-identity-services#36]
### Issue description

Hello Identity Services Documentaiton Team,

from the line [mta.yaml#L81](https://github.com/SAP-samples/appgyver-auth-flows/blob/main/demoAppRouter/mta.yaml#L81) I know that there is the oauth2-configuration parameter named grant-types. Unfortunately I can't find it documented on the Service Properties page. Especially the possible values should be documented.

Best Regards
Gregor

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Reference Information for the Identity Service of SAP BTP

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/reference-information-for-identity-service-of-sap-btp?locale=en-US&q=%22oauth2-configuration%22%20%22grant-types%22

**Comment by MichaelPShea** [comment]
Thanks Gregor. We'll update this documentation with the next release. The value types should be "client_credentials", "password", "urn:ietf:params:oauth:grant-type:jwt-bearer", "authorization_code", "implicit", "refresh_token", "urn:ietf:params:oauth:grant-type:token-exchange", "authorization_code_pkce_s256". But we will confirm this with the development team and add it to the documentation.

**Comment by MichaelPShea** [comment]
Backlog item created.
