### ISSUE TITLE
'Add' buton location is ambigious.

### ISSUE THREAD

**Issue by PV4SAP** [SAP-docs/btp-cloud-identity-services#41]
### Issue description

Saphelp states 
"Type the name of the CSS style in the search field to filter the list items, or choose the CSS style from the list on the left.
If you do not have a CSS style in your list, you can create one by choosing the Add button on the left-hand panel."

There is no ADD button anywhere on the screen. However same task could be achived if user go to top level menu 'Applications & Resources' and selects submenu 'Custom CSS' to upload a new CSS.

Same correction would also apply for Logo Image upload.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Use a Custom CSS

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/use-custom-css?locale=en-US

**Comment by ValAta** [comment]
Hi @PV4SAP ,
Thanks for your feedback. 
When you don't have CCSs in the admin console, you see this:
![CSS_Add_Button](https://github.com/user-attachments/assets/dd9bca2a-d2de-4084-a75f-ff5d6430d861)
 "Add button on the left-hand panel.", for sure the is no left-hand panel, this is already corrected, and will be updated with the next release of the document.
When you already have a list of CSSs you can follow the steps suggested by you and upload a new CSS:
![CustomCSSList](https://github.com/user-attachments/assets/81e799ec-3b0e-4767-85a6-8375b1b4ad62)
Actually using the submenu or the tiles from the home button leads to one and the same result. The whole documentation uses so far the tile approach. 
BR
