### ISSUE TITLE
Connectivity plan sub-accounts - need update with KSA DC opening?

### ISSUE THREAD

**Issue by kirillgromyko** [SAP-docs/btp-cloud-identity-services#42]
### Issue description

With the recent opening of BTP DC in the KSA, is the item 3 still valid for Identity Authentication Region in Riyadh? Can you please clarify if sub-account with connectivity plan is still supposed to be in AWS Frankfurt. Thank you.

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Connect to On-Premise Systems

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/connect-to-on-premise-systems-in-sap-cloud-identity-infrastructure

**Comment by kirillgromyko** [comment]
@IvelinaKiryakova , any update on this?

**Comment by IvelinaKiryakova** [comment]
Thank you for your question. We are still researching it and will get back to you once we have a clear confirmation.
Best regards,
Ivelina

**Comment by IvelinaKiryakova** [comment]
Hi Kirill,
I've checked your question with the Ops team. They confirmed that the subaccount with connectivity plan is still supposed to be in AWS Frankfurt. Documentation is correct.

They said that currently, if you create a subaccount in sa30, SAP Cloud Identity Services won't be available there and no connectivity plan would be activated.

Thank you and best regards,
Ivelina
