### ISSUE TITLE
Is it Possible the add more than 1 Subaccount?

### ISSUE THREAD

**Issue by SecAuth-G** [SAP-docs/btp-cloud-identity-services#44]
I have initially successfully connected a subaccount via the corresponding service in the Admin Console of the SAP Cloud Identity Service. Now I wanted to connect further subaccounts that are also in the correct region. However, the “add” button is permanently grayed out and I cannot add any more subaccounts. Does anyone know what the problem is here? Are there other limitations?

BR G

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Access Audit Logs (Audit Log Service in SAP BTP, Cloud Foundry)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/access-audit-logs-aws-azure-infrastructure?version=Cloud

**Comment by ValAta** [comment]
Hi @SecAuth-G,
Thanks for your comment. You can have only one configuration in the admin console. We have added that information in the document, and it will be updated with the next release of the documentation.
BR,
Valentin
