### ISSUE TITLE
Incorrect example for OAuth2TokenServiceURL

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/btp-cloud-identity-services#46]
### Issue description

Hello IPS Team,

the example URL for the Property Name `OAuth2TokenServiceURL` is currently https://demo-hc-3-test.authentication.sap.hana.ondemand.com. But that results in the error message:

> Connector cannot process more entities due to irreparable error Caused by: Could not retrieve OAuth token Caused by: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1],

The example should be `https://demo-hc-3-test.authentication.sap.hana.ondemand.com/oauth/token` to get a working auhentication.

Best Regards
Gregor

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

SAP HANA Cloud, SAP HANA Database

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/sap-hana-cloud-sap-hana-database-7e2b54ec36344dc1983d5f8a6437b11b?locale=en-US

**Comment by IvelinaKiryakova** [comment]
Hi Gregor, Thank you for noticing this. We have corrected the URL, and the update will be released shortly.

Best regards,
Ivelina
